// Psychoactive Substances Documentation - Auto-Generated Export File

// Re-export types
export type {
  Substance,
  SubstanceCategory,
  CategoryInfo,
  RouteDosageDuration
} from '../types';

// Re-export individual substances
export {
  _1_3_butanediol,
  _1p_eth_lad,
  _1cp_mipla,
  _1cp_al_lad,
  _1b_lsd,
  _1cp_lsd,
  _2_5_dma,
  _1v_lsd,
  _1p_lsd,
  _25c_nbome,
  _25c_nboh,
  _25d_nbome,
  _25b_nbome,
  _25i_nboh,
  _25i_nbome,
  _2c_b_fly,
  _2c_c,
  _2c_d,
  _25n_nbome,
  _2c_b,
  _2c_e,
  _2c_p,
  _2c_i,
  _2c_t,
  _2c_t_21,
  _2c_t_2,
  _2c_t_7,
  _3c_p,
  _3c_e,
  _4_aco_det,
  _4_aco_met,
  _4_aco_dmt,
  _4_aco_dipt,
  _4_aco_mipt,
  _4_ho_det,
  _4_ho_dpt,
  _4_ho_met,
  _4_ho_dipt,
  _4_ho_ept,
  _4_ho_mpt,
  _4_ho_mipt,
  _5_meo_dalt,
  _5_meo_dibf,
  _5_meo_dipt,
  _5_meo_dmt,
  _5_meo_mipt,
  _6_apb,
  al_lad,
  ald_52,
  allylescaline,
  ayahuasca,
  bufotenin,
  bromo_dragonfly,
  det,
  dob,
  dmt,
  doc,
  dom,
  doi,
  dpt,
  dipt,
  ept,
  eth_lad,
  efavirenz,
  escaline,
  ibogaine,
  lae_32,
  lsm_775,
  lsa,
  lsz,
  lsd,
  mpt,
  met,
  mda,
  methallylescaline,
  mescaline,
  mipt,
  mipla,
  pargy_lad,
  pro_lad,
  proscaline,
  psilocybin_mushrooms,
  psilocin,
  tma_2,
  tma_6,
  mt,
  k_2c_b,
  _2_aminoindane,
  _2_fea,
  _2_fa,
  _2_fma,
  _3_4_ctmp,
  _3_fa,
  _3_fpm,
  _3_fma,
  _3_fea,
  _3_mmc,
  _4_fa,
  _4_fma,
  _4f_eph,
  _4f_mph,
  _5_apb,
  _6_apdb,
  a_php,
  a_pvp,
  adrafinil,
  amphetamine,
  armodafinil,
  benzydamine,
  bromantane,
  butylone,
  caffeine,
  cyclazodone,
  cocaine,
  desoxypipradrol,
  dextroamphetamine,
  dichloropane,
  eth_cat,
  ephedrine,
  ephylone,
  ethylphenidate,
  ethylone,
  fenethylline,
  hexedrone,
  isopropylphenidate,
  kratom,
  lisdexamfetamine,
  mcpp,
  mdpv,
  mdma,
  mephedrone,
  methcathinone,
  methamphetamine,
  methiopropamine,
  methylone,
  methylnaphthidate,
  methylphenidate,
  mexedrone,
  modafinil,
  n_methylbisfluoromodafinil,
  n_ethylhexedrone,
  nm_2_ai,
  nep,
  nicotine,
  oxiracetam,
  pentedrone,
  phenylpiracetam,
  prolintane,
  propylhexedrine,
  theacrine,
  tyrosine,
  _1_4_butanediol,
  _2m2b,
  alcohol,
  alprazolam,
  baclofen,
  cake,
  carisoprodol,
  clonazepam,
  clonidine,
  clonazolam,
  deschloroetizolam,
  diazepam,
  diclazepam,
  eszopiclone,
  etizolam,
  f_phenibut,
  flubromazepam,
  flualprazolam,
  flunitrazepam,
  flubromazolam,
  flunitrazolam,
  gbl,
  ghb,
  grayanotoxin,
  gabapentin,
  gaboxadol,
  lorazepam,
  mephenaqualone,
  methaqualone,
  metizolam,
  midazolam,
  mirtazapine,
  nifoxipam,
  pentobarbital,
  phenobarbital,
  phenibut,
  pregabalin,
  promethazine,
  progesterone,
  pyrazolam,
  secobarbital,
  temazepam,
  tizanidine,
  zopiclone,
  zolpidem,
  _2_fluorodeschloroketamine,
  _3_ho_pce,
  _3_ho_pcp,
  _3_meo_pcmo,
  _3_meo_pce,
  _3_meo_pcp,
  _4_meo_pcp,
  deschloroketamine,
  dextromethorphan,
  diphenidine,
  ephenidine,
  hxe,
  ketamine,
  mxipr,
  memantine,
  methoxetamine,
  methoxphenidine,
  nitrous,
  o_pce,
  pce,
  pcp,
  rolicyclidine,
  _5_mapb,
  mdai,
  mdea,
  pma,
  pmma,
  _5f_akb48,
  _5f_pb_22,
  ab_fubinaca,
  apica,
  cannabidiol,
  jwh_018,
  jwh_073,
  sts_135,
  thj_018,
  thj_2201,
  acetylfentanyl,
  buprenorphine,
  codeine,
  desomorphine,
  dextropropoxyphene,
  dihydrocodeine,
  ethylmorphine,
  fentanyl,
  hydrocodone,
  hydromorphone,
  heroin,
  methadone,
  morphine,
  naloxone,
  o_desmethyltramadol,
  oxycodone,
  oxymorphone,
  pethidine,
  sufentanil,
  tapentadol,
  tianeptine,
  tramadol,
  u_47700,
  datura,
  diphenhydramine,
  myristicin,
  _5_hydroxytryptophan,
  alpha_gpc,
  aniracetam,
  citicoline,
  choline_bitartrate,
  creatine,
  coluracetam,
  galantamine,
  meclofenoxate,
  _7_hydroxymitragynine,
  n_acetylcysteine,
  omberacetam,
  piracetam,
  pramiracetam,
  sam_e,
  theanine,
  blue_lotus,
  bromazepam,
  cannabis
} from './substances';

// Import for helper functions
import { Substance, SubstanceCategory } from '../types';
import {
  _1_3_butanediol,
  _1p_eth_lad,
  _1cp_mipla,
  _1cp_al_lad,
  _1b_lsd,
  _1cp_lsd,
  _2_5_dma,
  _1v_lsd,
  _1p_lsd,
  _25c_nbome,
  _25c_nboh,
  _25d_nbome,
  _25b_nbome,
  _25i_nboh,
  _25i_nbome,
  _2c_b_fly,
  _2c_c,
  _2c_d,
  _25n_nbome,
  _2c_b,
  _2c_e,
  _2c_p,
  _2c_i,
  _2c_t,
  _2c_t_21,
  _2c_t_2,
  _2c_t_7,
  _3c_p,
  _3c_e,
  _4_aco_det,
  _4_aco_met,
  _4_aco_dmt,
  _4_aco_dipt,
  _4_aco_mipt,
  _4_ho_det,
  _4_ho_dpt,
  _4_ho_met,
  _4_ho_dipt,
  _4_ho_ept,
  _4_ho_mpt,
  _4_ho_mipt,
  _5_meo_dalt,
  _5_meo_dibf,
  _5_meo_dipt,
  _5_meo_dmt,
  _5_meo_mipt,
  _6_apb,
  al_lad,
  ald_52,
  allylescaline,
  ayahuasca,
  bufotenin,
  bromo_dragonfly,
  det,
  dob,
  dmt,
  doc,
  dom,
  doi,
  dpt,
  dipt,
  ept,
  eth_lad,
  efavirenz,
  escaline,
  ibogaine,
  lae_32,
  lsm_775,
  lsa,
  lsz,
  lsd,
  mpt,
  met,
  mda,
  methallylescaline,
  mescaline,
  mipt,
  mipla,
  pargy_lad,
  pro_lad,
  proscaline,
  psilocybin_mushrooms,
  psilocin,
  tma_2,
  tma_6,
  mt,
  k_2c_b,
  _2_aminoindane,
  _2_fea,
  _2_fa,
  _2_fma,
  _3_4_ctmp,
  _3_fa,
  _3_fpm,
  _3_fma,
  _3_fea,
  _3_mmc,
  _4_fa,
  _4_fma,
  _4f_eph,
  _4f_mph,
  _5_apb,
  _6_apdb,
  a_php,
  a_pvp,
  adrafinil,
  amphetamine,
  armodafinil,
  benzydamine,
  bromantane,
  butylone,
  caffeine,
  cyclazodone,
  cocaine,
  desoxypipradrol,
  dextroamphetamine,
  dichloropane,
  eth_cat,
  ephedrine,
  ephylone,
  ethylphenidate,
  ethylone,
  fenethylline,
  hexedrone,
  isopropylphenidate,
  kratom,
  _7_hydroxymitragynine,
  lisdexamfetamine,
  mcpp,
  mdpv,
  mdma,
  mephedrone,
  methcathinone,
  methamphetamine,
  methiopropamine,
  methylone,
  methylnaphthidate,
  methylphenidate,
  mexedrone,
  modafinil,
  n_methylbisfluoromodafinil,
  n_ethylhexedrone,
  nm_2_ai,
  nep,
  nicotine,
  oxiracetam,
  pentedrone,
  phenylpiracetam,
  prolintane,
  propylhexedrine,
  theacrine,
  tyrosine,
  _1_4_butanediol,
  _2m2b,
  alcohol,
  alprazolam,
  baclofen,
  cake,
  carisoprodol,
  clonazepam,
  clonidine,
  clonazolam,
  deschloroetizolam,
  diazepam,
  diclazepam,
  eszopiclone,
  etizolam,
  f_phenibut,
  flubromazepam,
  flualprazolam,
  flunitrazepam,
  flubromazolam,
  flunitrazolam,
  gbl,
  ghb,
  grayanotoxin,
  gabapentin,
  gaboxadol,
  lorazepam,
  mephenaqualone,
  methaqualone,
  metizolam,
  midazolam,
  mirtazapine,
  nifoxipam,
  pentobarbital,
  phenobarbital,
  phenibut,
  pregabalin,
  promethazine,
  progesterone,
  pyrazolam,
  secobarbital,
  temazepam,
  tizanidine,
  zopiclone,
  zolpidem,
  _2_fluorodeschloroketamine,
  _3_ho_pce,
  _3_ho_pcp,
  _3_meo_pcmo,
  _3_meo_pce,
  _3_meo_pcp,
  _4_meo_pcp,
  deschloroketamine,
  dextromethorphan,
  diphenidine,
  ephenidine,
  hxe,
  ketamine,
  mxipr,
  memantine,
  methoxetamine,
  methoxphenidine,
  nitrous,
  o_pce,
  pce,
  pcp,
  rolicyclidine,
  _5_mapb,
  mdai,
  mdea,
  pma,
  pmma,
  _5f_akb48,
  _5f_pb_22,
  ab_fubinaca,
  apica,
  cannabidiol,
  jwh_018,
  jwh_073,
  sts_135,
  thj_018,
  thj_2201,
  acetylfentanyl,
  buprenorphine,
  codeine,
  desomorphine,
  dextropropoxyphene,
  dihydrocodeine,
  ethylmorphine,
  fentanyl,
  hydrocodone,
  hydromorphone,
  heroin,
  methadone,
  morphine,
  naloxone,
  o_desmethyltramadol,
  oxycodone,
  oxymorphone,
  pethidine,
  sufentanil,
  tapentadol,
  tianeptine,
  tramadol,
  u_47700,
  datura,
  diphenhydramine,
  myristicin,
  _5_hydroxytryptophan,
  alpha_gpc,
  aniracetam,
  citicoline,
  choline_bitartrate,
  creatine,
  coluracetam,
  galantamine,
  meclofenoxate,
  n_acetylcysteine,
  omberacetam,
  piracetam,
  pramiracetam,
  sam_e,
  theanine,
  blue_lotus,
  bromazepam,
  cannabis
} from './substances';

// All substances combined into a single array
export const substances: Substance[] = [
  _1_3_butanediol,
  _1p_eth_lad,
  _1cp_mipla,
  _1cp_al_lad,
  _1b_lsd,
  _1cp_lsd,
  _2_5_dma,
  _1v_lsd,
  _1p_lsd,
  _25c_nbome,
  _25c_nboh,
  _25d_nbome,
  _25b_nbome,
  _25i_nboh,
  _25i_nbome,
  _2c_b_fly,
  _2c_c,
  _2c_d,
  _25n_nbome,
  _2c_b,
  _2c_e,
  _2c_p,
  _2c_i,
  _2c_t,
  _2c_t_21,
  _2c_t_2,
  _2c_t_7,
  _3c_p,
  _3c_e,
  _4_aco_det,
  _4_aco_met,
  _4_aco_dmt,
  _4_aco_dipt,
  _4_aco_mipt,
  _4_ho_det,
  _4_ho_dpt,
  _4_ho_met,
  _4_ho_dipt,
  _4_ho_ept,
  _4_ho_mpt,
  _4_ho_mipt,
  _5_meo_dalt,
  _5_meo_dibf,
  _5_meo_dipt,
  _5_meo_dmt,
  _5_meo_mipt,
  _6_apb,
  al_lad,
  ald_52,
  allylescaline,
  ayahuasca,
  bufotenin,
  bromo_dragonfly,
  det,
  dob,
  dmt,
  doc,
  dom,
  doi,
  dpt,
  dipt,
  ept,
  eth_lad,
  efavirenz,
  escaline,
  ibogaine,
  lae_32,
  lsm_775,
  lsa,
  lsz,
  lsd,
  mpt,
  met,
  mda,
  methallylescaline,
  mescaline,
  mipt,
  mipla,
  pargy_lad,
  pro_lad,
  proscaline,
  psilocybin_mushrooms,
  psilocin,
  tma_2,
  tma_6,
  mt,
  k_2c_b,
  _2_aminoindane,
  _2_fea,
  _2_fa,
  _2_fma,
  _3_4_ctmp,
  _3_fa,
  _3_fpm,
  _3_fma,
  _3_fea,
  _3_mmc,
  _4_fa,
  _4_fma,
  _4f_eph,
  _4f_mph,
  _5_apb,
  _6_apdb,
  a_php,
  a_pvp,
  adrafinil,
  amphetamine,
  armodafinil,
  benzydamine,
  bromantane,
  butylone,
  caffeine,
  cyclazodone,
  cocaine,
  desoxypipradrol,
  dextroamphetamine,
  dichloropane,
  eth_cat,
  ephedrine,
  ephylone,
  ethylphenidate,
  ethylone,
  fenethylline,
  hexedrone,
  isopropylphenidate,
  kratom,
  lisdexamfetamine,
  mcpp,
  mdpv,
  _7_hydroxymitragynine,
  mdma,
  mephedrone,
  methcathinone,
  methamphetamine,
  methiopropamine,
  methylone,
  methylnaphthidate,
  methylphenidate,
  mexedrone,
  modafinil,
  n_methylbisfluoromodafinil,
  n_ethylhexedrone,
  nm_2_ai,
  nep,
  nicotine,
  oxiracetam,
  pentedrone,
  phenylpiracetam,
  prolintane,
  propylhexedrine,
  theacrine,
  tyrosine,
  _1_4_butanediol,
  _2m2b,
  alcohol,
  alprazolam,
  baclofen,
  cake,
  carisoprodol,
  clonazepam,
  clonidine,
  clonazolam,
  deschloroetizolam,
  diazepam,
  diclazepam,
  eszopiclone,
  etizolam,
  f_phenibut,
  flubromazepam,
  flualprazolam,
  flunitrazepam,
  flubromazolam,
  flunitrazolam,
  gbl,
  ghb,
  grayanotoxin,
  gabapentin,
  gaboxadol,
  lorazepam,
  mephenaqualone,
  methaqualone,
  metizolam,
  midazolam,
  mirtazapine,
  nifoxipam,
  pentobarbital,
  phenobarbital,
  phenibut,
  pregabalin,
  promethazine,
  progesterone,
  pyrazolam,
  secobarbital,
  temazepam,
  tizanidine,
  zopiclone,
  zolpidem,
  _2_fluorodeschloroketamine,
  _3_ho_pce,
  _3_ho_pcp,
  _3_meo_pcmo,
  _3_meo_pce,
  _3_meo_pcp,
  _4_meo_pcp,
  deschloroketamine,
  dextromethorphan,
  diphenidine,
  ephenidine,
  hxe,
  ketamine,
  mxipr,
  memantine,
  methoxetamine,
  methoxphenidine,
  nitrous,
  o_pce,
  pce,
  pcp,
  rolicyclidine,
  _5_mapb,
  mdai,
  mdea,
  pma,
  pmma,
  _5f_akb48,
  _5f_pb_22,
  ab_fubinaca,
  apica,
  cannabidiol,
  jwh_018,
  jwh_073,
  sts_135,
  thj_018,
  thj_2201,
  acetylfentanyl,
  buprenorphine,
  codeine,
  desomorphine,
  dextropropoxyphene,
  dihydrocodeine,
  ethylmorphine,
  fentanyl,
  hydrocodone,
  hydromorphone,
  heroin,
  methadone,
  morphine,
  naloxone,
  o_desmethyltramadol,
  oxycodone,
  oxymorphone,
  pethidine,
  sufentanil,
  tapentadol,
  tianeptine,
  tramadol,
  u_47700,
  datura,
  diphenhydramine,
  myristicin,
  _5_hydroxytryptophan,
  alpha_gpc,
  aniracetam,
  citicoline,
  choline_bitartrate,
  creatine,
  coluracetam,
  galantamine,
  meclofenoxate,
  n_acetylcysteine,
  omberacetam,
  piracetam,
  pramiracetam,
  sam_e,
  theanine,
  blue_lotus,
  bromazepam,
  cannabis
];

// Map for quick category lookup
const substancesByCategory: Record<string, Substance[]> = {
  'cannabinoids': [
    _5f_akb48,
    _5f_pb_22,
    ab_fubinaca,
    apica,
    cannabidiol,
    jwh_018,
    jwh_073,
    sts_135,
    thj_018,
    thj_2201
  ],
  'deliriants': [
    benzydamine,
    mirtazapine,
    promethazine,
    datura,
    diphenhydramine,
    myristicin
  ],
  'depressants': [
    nicotine,
    _1_4_butanediol,
    _2m2b,
    alcohol,
    alprazolam,
    baclofen,
    cake,
    carisoprodol,
    clonazepam,
    clonidine,
    clonazolam,
    deschloroetizolam,
    diazepam,
    diclazepam,
    eszopiclone,
    etizolam,
    f_phenibut,
    flubromazepam,
    flualprazolam,
    flunitrazepam,
    flubromazolam,
    flunitrazolam,
    gbl,
    ghb,
    grayanotoxin,
    gabapentin,
    gaboxadol,
    lorazepam,
    mephenaqualone,
    methaqualone,
    metizolam,
    midazolam,
    mirtazapine,
    nifoxipam,
    pentobarbital,
    phenobarbital,
    phenibut,
    pregabalin,
    promethazine,
    progesterone,
    pyrazolam,
    secobarbital,
    temazepam,
    tizanidine,
    zopiclone,
    zolpidem
  ],
  'dissociatives': [
    _2_fluorodeschloroketamine,
    _3_ho_pce,
    _3_ho_pcp,
    _3_meo_pcmo,
    _3_meo_pce,
    _3_meo_pcp,
    _4_meo_pcp,
    deschloroketamine,
    dextromethorphan,
    diphenidine,
    ephenidine,
    hxe,
    ketamine,
    mxipr,
    memantine,
    methoxetamine,
    methoxphenidine,
    nitrous,
    o_pce,
    pce,
    pcp,
    rolicyclidine
  ],
  'empathogens': [
    _5_meo_mipt,
    _6_apb,
    mda,
    mt,
    _2_fea,
    _3_fma,
    _3_fea,
    _3_mmc,
    _4_fa,
    _4_fma,
    _5_apb,
    _6_apdb,
    butylone,
    ephylone,
    mdpv,
    mdma,
    mephedrone,
    methcathinone,
    methylone,
    _5_mapb,
    mdai,
    mdea,
    pma,
    pmma
  ],
  'hallucinogens': [
    _1_3_butanediol,
    _1p_eth_lad,
    _1cp_mipla,
    _1cp_al_lad,
    _1b_lsd,
    _1cp_lsd,
    _2_5_dma,
    _1v_lsd,
    _1p_lsd,
    _25c_nbome,
    _25c_nboh,
    _25d_nbome,
    _25b_nbome,
    _25i_nboh,
    _25i_nbome,
    _2c_b_fly,
    _2c_c,
    _2c_d,
    _25n_nbome,
    _2c_b,
    _2c_e,
    _2c_p,
    _2c_i,
    _2c_t,
    _2c_t_21,
    _2c_t_2,
    _2c_t_7,
    _3c_p,
    _3c_e,
    _4_aco_det,
    _4_aco_met,
    _4_aco_dmt,
    _4_aco_dipt,
    _4_aco_mipt,
    _4_ho_det,
    _4_ho_dpt,
    _4_ho_met,
    _4_ho_dipt,
    _4_ho_ept,
    _4_ho_mpt,
    _4_ho_mipt,
    _5_meo_dalt,
    _5_meo_dibf,
    _5_meo_dipt,
    _5_meo_dmt,
    _5_meo_mipt,
    _6_apb,
    al_lad,
    ald_52,
    allylescaline,
    ayahuasca,
    bufotenin,
    bromo_dragonfly,
    det,
    dob,
    dmt,
    doc,
    dom,
    doi,
    dpt,
    dipt,
    ept,
    eth_lad,
    efavirenz,
    escaline,
    ibogaine,
    lae_32,
    lsm_775,
    lsa,
    lsz,
    lsd,
    mpt,
    met,
    mda,
    methallylescaline,
    mescaline,
    mipt,
    mipla,
    pargy_lad,
    pro_lad,
    proscaline,
    psilocybin_mushrooms,
    psilocin,
    tma_2,
    tma_6,
    mt,
    k_2c_b
  ],
  'nootropics': [
    adrafinil,
    bromantane,
    n_methylbisfluoromodafinil,
    oxiracetam,
    phenylpiracetam,
    theacrine,
    tianeptine,
    _5_hydroxytryptophan,
    alpha_gpc,
    aniracetam,
    citicoline,
    choline_bitartrate,
    creatine,
    coluracetam,
    galantamine,
    meclofenoxate,
    n_acetylcysteine,
    omberacetam,
    piracetam,
    pramiracetam,
    sam_e,
    theanine
  ],
  'opioids': [
    kratom,
    _7_hydroxymitragynine,
    acetylfentanyl,
    buprenorphine,
    codeine,
    desomorphine,
    dextropropoxyphene,
    dihydrocodeine,
    ethylmorphine,
    fentanyl,
    hydrocodone,
    hydromorphone,
    heroin,
    methadone,
    morphine,
    naloxone,
    o_desmethyltramadol,
    oxycodone,
    oxymorphone,
    pethidine,
    sufentanil,
    tapentadol,
    tianeptine,
    tramadol,
    u_47700
  ],
  'other': [
    blue_lotus,
    bromazepam,
    cannabis
  ],
  'stimulants': [
    _2_5_dma,
    mda,
    tma_2,
    tma_6,
    _2_aminoindane,
    _2_fea,
    _2_fa,
    _2_fma,
    _3_4_ctmp,
    _3_fa,
    _3_fpm,
    _3_fma,
    _3_fea,
    _3_mmc,
    _4_fa,
    _4_fma,
    _4f_eph,
    _4f_mph,
    _5_apb,
    _6_apdb,
    a_php,
    a_pvp,
    adrafinil,
    amphetamine,
    armodafinil,
    benzydamine,
    bromantane,
    butylone,
    caffeine,
    cyclazodone,
    cocaine,
    desoxypipradrol,
    dextroamphetamine,
    dichloropane,
    eth_cat,
    ephedrine,
    ephylone,
    ethylphenidate,
    ethylone,
    fenethylline,
    hexedrone,
    isopropylphenidate,
    kratom,
    lisdexamfetamine,
    mcpp,
    mdpv,
    mdma,
    mephedrone,
    methcathinone,
    methamphetamine,
    methiopropamine,
    methylone,
    methylnaphthidate,
    methylphenidate,
    mexedrone,
    modafinil,
    n_methylbisfluoromodafinil,
    n_ethylhexedrone,
    nm_2_ai,
    nep,
    nicotine,
    oxiracetam,
    pentedrone,
    phenylpiracetam,
    prolintane,
    propylhexedrine,
    theacrine,
    tyrosine
  ]
};

// Map for quick ID lookup
const substancesById: Record<string, Substance> = {
  '1-3-butanediol': _1_3_butanediol,
  '1p-eth-lad': _1p_eth_lad,
  '1cp-mipla': _1cp_mipla,
  '1cp-al-lad': _1cp_al_lad,
  '1b-lsd': _1b_lsd,
  '1cp-lsd': _1cp_lsd,
  '2-5-dma': _2_5_dma,
  '1v-lsd': _1v_lsd,
  '1p-lsd': _1p_lsd,
  '7-hydroxymitragynine': _7_hydroxymitragynine,
  '25c-nbome': _25c_nbome,
  '25c-nboh': _25c_nboh,
  '25d-nbome': _25d_nbome,
  '25b-nbome': _25b_nbome,
  '25i-nboh': _25i_nboh,
  '25i-nbome': _25i_nbome,
  '2c-b-fly': _2c_b_fly,
  '2c-c': _2c_c,
  '2c-d': _2c_d,
  '25n-nbome': _25n_nbome,
  '2c-b': _2c_b,
  '2c-e': _2c_e,
  '2c-p': _2c_p,
  '2c-i': _2c_i,
  '2c-t': _2c_t,
  '2c-t-21': _2c_t_21,
  '2c-t-2': _2c_t_2,
  '2c-t-7': _2c_t_7,
  '3c-p': _3c_p,
  '3c-e': _3c_e,
  '4-aco-det': _4_aco_det,
  '4-aco-met': _4_aco_met,
  '4-aco-dmt': _4_aco_dmt,
  '4-aco-dipt': _4_aco_dipt,
  '4-aco-mipt': _4_aco_mipt,
  '4-ho-det': _4_ho_det,
  '4-ho-dpt': _4_ho_dpt,
  '4-ho-met': _4_ho_met,
  '4-ho-dipt': _4_ho_dipt,
  '4-ho-ept': _4_ho_ept,
  '4-ho-mpt': _4_ho_mpt,
  '4-ho-mipt': _4_ho_mipt,
  '5-meo-dalt': _5_meo_dalt,
  '5-meo-dibf': _5_meo_dibf,
  '5-meo-dipt': _5_meo_dipt,
  '5-meo-dmt': _5_meo_dmt,
  '5-meo-mipt': _5_meo_mipt,
  '6-apb': _6_apb,
  'al-lad': al_lad,
  'ald-52': ald_52,
  'allylescaline': allylescaline,
  'ayahuasca': ayahuasca,
  'bufotenin': bufotenin,
  'bromo-dragonfly': bromo_dragonfly,
  'det': det,
  'dob': dob,
  'dmt': dmt,
  'doc': doc,
  'dom': dom,
  'doi': doi,
  'dpt': dpt,
  'dipt': dipt,
  'ept': ept,
  'eth-lad': eth_lad,
  'efavirenz': efavirenz,
  'escaline': escaline,
  'ibogaine': ibogaine,
  'lae-32': lae_32,
  'lsm-775': lsm_775,
  'lsa': lsa,
  'lsz': lsz,
  'lsd': lsd,
  'mpt': mpt,
  'met': met,
  'mda': mda,
  'methallylescaline': methallylescaline,
  'mescaline': mescaline,
  'mipt': mipt,
  'mipla': mipla,
  'pargy-lad': pargy_lad,
  'pro-lad': pro_lad,
  'proscaline': proscaline,
  'psilocybin-mushrooms': psilocybin_mushrooms,
  'psilocin': psilocin,
  'tma-2': tma_2,
  'tma-6': tma_6,
  'mt': mt,
  'k-2c-b': k_2c_b,
  '2-aminoindane': _2_aminoindane,
  '2-fea': _2_fea,
  '2-fa': _2_fa,
  '2-fma': _2_fma,
  '3-4-ctmp': _3_4_ctmp,
  '3-fa': _3_fa,
  '3-fpm': _3_fpm,
  '3-fma': _3_fma,
  '3-fea': _3_fea,
  '3-mmc': _3_mmc,
  '4-fa': _4_fa,
  '4-fma': _4_fma,
  '4f-eph': _4f_eph,
  '4f-mph': _4f_mph,
  '5-apb': _5_apb,
  '6-apdb': _6_apdb,
  'a-php': a_php,
  'a-pvp': a_pvp,
  'adrafinil': adrafinil,
  'amphetamine': amphetamine,
  'armodafinil': armodafinil,
  'benzydamine': benzydamine,
  'bromantane': bromantane,
  'butylone': butylone,
  'caffeine': caffeine,
  'cyclazodone': cyclazodone,
  'cocaine': cocaine,
  'desoxypipradrol': desoxypipradrol,
  'dextroamphetamine': dextroamphetamine,
  'dichloropane': dichloropane,
  'eth-cat': eth_cat,
  'ephedrine': ephedrine,
  'ephylone': ephylone,
  'ethylphenidate': ethylphenidate,
  'ethylone': ethylone,
  'fenethylline': fenethylline,
  'hexedrone': hexedrone,
  'isopropylphenidate': isopropylphenidate,
  'kratom': kratom,
  'lisdexamfetamine': lisdexamfetamine,
  'mcpp': mcpp,
  'mdpv': mdpv,
  'mdma': mdma,
  'mephedrone': mephedrone,
  'methcathinone': methcathinone,
  'methamphetamine': methamphetamine,
  'methiopropamine': methiopropamine,
  'methylone': methylone,
  'methylnaphthidate': methylnaphthidate,
  'methylphenidate': methylphenidate,
  'mexedrone': mexedrone,
  'modafinil': modafinil,
  'n-methylbisfluoromodafinil': n_methylbisfluoromodafinil,
  'n-ethylhexedrone': n_ethylhexedrone,
  'nm-2-ai': nm_2_ai,
  'nep': nep,
  'nicotine': nicotine,
  'oxiracetam': oxiracetam,
  'pentedrone': pentedrone,
  'phenylpiracetam': phenylpiracetam,
  'prolintane': prolintane,
  'propylhexedrine': propylhexedrine,
  'theacrine': theacrine,
  'tyrosine': tyrosine,
  '1-4-butanediol': _1_4_butanediol,
  '2m2b': _2m2b,
  'alcohol': alcohol,
  'alprazolam': alprazolam,
  'baclofen': baclofen,
  'cake': cake,
  'carisoprodol': carisoprodol,
  'clonazepam': clonazepam,
  'clonidine': clonidine,
  'clonazolam': clonazolam,
  'deschloroetizolam': deschloroetizolam,
  'diazepam': diazepam,
  'diclazepam': diclazepam,
  'eszopiclone': eszopiclone,
  'etizolam': etizolam,
  'f-phenibut': f_phenibut,
  'flubromazepam': flubromazepam,
  'flualprazolam': flualprazolam,
  'flunitrazepam': flunitrazepam,
  'flubromazolam': flubromazolam,
  'flunitrazolam': flunitrazolam,
  'gbl': gbl,
  'ghb': ghb,
  'grayanotoxin': grayanotoxin,
  'gabapentin': gabapentin,
  'gaboxadol': gaboxadol,
  'lorazepam': lorazepam,
  'mephenaqualone': mephenaqualone,
  'methaqualone': methaqualone,
  'metizolam': metizolam,
  'midazolam': midazolam,
  'mirtazapine': mirtazapine,
  'nifoxipam': nifoxipam,
  'pentobarbital': pentobarbital,
  'phenobarbital': phenobarbital,
  'phenibut': phenibut,
  'pregabalin': pregabalin,
  'promethazine': promethazine,
  'progesterone': progesterone,
  'pyrazolam': pyrazolam,
  'secobarbital': secobarbital,
  'temazepam': temazepam,
  'tizanidine': tizanidine,
  'zopiclone': zopiclone,
  'zolpidem': zolpidem,
  '2-fluorodeschloroketamine': _2_fluorodeschloroketamine,
  '3-ho-pce': _3_ho_pce,
  '3-ho-pcp': _3_ho_pcp,
  '3-meo-pcmo': _3_meo_pcmo,
  '3-meo-pce': _3_meo_pce,
  '3-meo-pcp': _3_meo_pcp,
  '4-meo-pcp': _4_meo_pcp,
  'deschloroketamine': deschloroketamine,
  'dextromethorphan': dextromethorphan,
  'diphenidine': diphenidine,
  'ephenidine': ephenidine,
  'hxe': hxe,
  'ketamine': ketamine,
  'mxipr': mxipr,
  'memantine': memantine,
  'methoxetamine': methoxetamine,
  'methoxphenidine': methoxphenidine,
  'nitrous': nitrous,
  'o-pce': o_pce,
  'pce': pce,
  'pcp': pcp,
  'rolicyclidine': rolicyclidine,
  '5-mapb': _5_mapb,
  'mdai': mdai,
  'mdea': mdea,
  'pma': pma,
  'pmma': pmma,
  '5f-akb48': _5f_akb48,
  '5f-pb-22': _5f_pb_22,
  'ab-fubinaca': ab_fubinaca,
  'apica': apica,
  'cannabidiol': cannabidiol,
  'jwh-018': jwh_018,
  'jwh-073': jwh_073,
  'sts-135': sts_135,
  'thj-018': thj_018,
  'thj-2201': thj_2201,
  'acetylfentanyl': acetylfentanyl,
  'buprenorphine': buprenorphine,
  'codeine': codeine,
  'desomorphine': desomorphine,
  'dextropropoxyphene': dextropropoxyphene,
  'dihydrocodeine': dihydrocodeine,
  'ethylmorphine': ethylmorphine,
  'fentanyl': fentanyl,
  'hydrocodone': hydrocodone,
  'hydromorphone': hydromorphone,
  'heroin': heroin,
  'methadone': methadone,
  'morphine': morphine,
  'naloxone': naloxone,
  'o-desmethyltramadol': o_desmethyltramadol,
  'oxycodone': oxycodone,
  'oxymorphone': oxymorphone,
  'pethidine': pethidine,
  'sufentanil': sufentanil,
  'tapentadol': tapentadol,
  'tianeptine': tianeptine,
  'tramadol': tramadol,
  'u-47700': u_47700,
  'datura': datura,
  'diphenhydramine': diphenhydramine,
  'myristicin': myristicin,
  '5-hydroxytryptophan': _5_hydroxytryptophan,
  'alpha-gpc': alpha_gpc,
  'aniracetam': aniracetam,
  'citicoline': citicoline,
  'choline-bitartrate': choline_bitartrate,
  'creatine': creatine,
  'coluracetam': coluracetam,
  'galantamine': galantamine,
  'meclofenoxate': meclofenoxate,
  'n-acetylcysteine': n_acetylcysteine,
  'omberacetam': omberacetam,
  'piracetam': piracetam,
  'pramiracetam': pramiracetam,
  'sam-e': sam_e,
  'theanine': theanine,
  'blue-lotus': blue_lotus,
  'bromazepam': bromazepam,
  'cannabis': cannabis
};

/**
 * Get a substance by its unique ID
 */
export function getSubstanceById(id: string): Substance | undefined {
  return substancesById[id];
}

/**
 * Get all substances in a specific category
 */
export function getSubstancesByCategory(category: string): Substance[] {
  return substancesByCategory[category] || [];
}

/**
 * Search substances by name, common names, aliases, or description
 */
export function searchSubstances(query: string): Substance[] {
  const lowerQuery = query.toLowerCase().trim();
  if (!lowerQuery) return [];
  
  return substances.filter(s =>
    s.name.toLowerCase().includes(lowerQuery) ||
    (s.commonNames || []).some((n: string) => n.toLowerCase().includes(lowerQuery)) ||
    (s.aliases || []).some((a: string) => a.toLowerCase().includes(lowerQuery)) ||
    s.description.toLowerCase().includes(lowerQuery)
  );
}

/**
 * Search substances with relevance ranking and fuzzy matching.
 * Returns results sorted by relevance score (highest first).
 * 
 * Scoring tiers:
 *  1000 — Exact name match
 *   800 — Name starts with query
 *   700 — Exact common name or alias match
 *   600 — Common name or alias starts with query
 *   400 — Name contains query as a whole word
 *   300 — Common name / alias contains query as a whole word
 *   200 — Name contains query as substring
 *   150 — Common name / alias contains query as substring
 *   100 — Class contains query
 *    80 — Category contains query
 *    50 — Description contains query
 *   -10 — Fuzzy match (Levenshtein distance, bonus for closer match)
 */
export function searchSubstancesRanked(
  query: string,
  options?: {
    categoryFilter?: string | null;
    limit?: number;
  }
): { substance: Substance; score: number; matchField: string }[] {
  const lowerQuery = query.toLowerCase().trim();
  if (!lowerQuery) return [];

  const { categoryFilter, limit = 50 } = options || {};
  const scored: { substance: Substance; score: number; matchField: string }[] = [];

  for (const s of substances) {
    // Apply category filter early
    if (categoryFilter && !(s.categories || []).includes(categoryFilter as any)) {
      continue;
    }

    let bestScore = 0;
    let bestField = '';

    // 1. Exact name match
    if (s.name.toLowerCase() === lowerQuery) {
      bestScore = 1000;
      bestField = 'name';
    }
    // 2. Name starts with query
    else if (s.name.toLowerCase().startsWith(lowerQuery)) {
      bestScore = 800;
      bestField = 'name';
    }

    // 3. Exact common name / alias
    if (bestScore < 700) {
      const allNames = [...(s.commonNames || []), ...(s.aliases || [])];
      for (const n of allNames) {
        const nLower = n.toLowerCase();
        if (nLower === lowerQuery && bestScore < 700) {
          bestScore = 700;
          bestField = n.length <= 15 ? n : 'name';
          break;
        }
        if (nLower.startsWith(lowerQuery) && bestScore < 600) {
          bestScore = 600;
          bestField = n.length <= 15 ? n : 'name';
        }
      }
    }

    // 4. Word-boundary match in name
    if (bestScore < 400) {
      const wordRe = new RegExp(`(?:^|\\s)${escapeSearchRegex(lowerQuery)}`, 'i');
      if (wordRe.test(s.name)) {
        bestScore = 400;
        bestField = 'name';
      }
    }

    // 5. Word-boundary match in common names / aliases
    if (bestScore < 300) {
      const allNames = [...(s.commonNames || []), ...(s.aliases || [])];
      for (const n of allNames) {
        const wordRe = new RegExp(`(?:^|\\s)${escapeSearchRegex(lowerQuery)}`, 'i');
        if (wordRe.test(n) && bestScore < 300) {
          bestScore = 300;
          bestField = n.length <= 15 ? n : 'name';
          break;
        }
      }
    }

    // 6. Substring in name
    if (bestScore < 200) {
      if (s.name.toLowerCase().includes(lowerQuery)) {
        bestScore = 200;
        bestField = 'name';
      }
    }

    // 7. Substring in common names / aliases
    if (bestScore < 150) {
      const allNames = [...(s.commonNames || []), ...(s.aliases || [])];
      for (const n of allNames) {
        if (n.toLowerCase().includes(lowerQuery) && bestScore < 150) {
          bestScore = 150;
          bestField = n.length <= 15 ? n : 'name';
          break;
        }
      }
    }

    // 8. Class match
    if (bestScore < 100) {
      if (s.class && s.class.toLowerCase().includes(lowerQuery)) {
        bestScore = 100;
        bestField = 'class';
      }
    }

    // 9. Category match
    if (bestScore < 80) {
      if ((s.categories || []).some((c: string) => c.toLowerCase().includes(lowerQuery))) {
        bestScore = 80;
        bestField = 'category';
      }
    }

    // 10. Description match
    if (bestScore < 50) {
      if (s.description && s.description.toLowerCase().includes(lowerQuery)) {
        bestScore = 50;
        bestField = 'description';
      }
    }

    // 11. Fuzzy matching (Levenshtein) — only for queries 3+ chars
    if (bestScore < 1 && lowerQuery.length >= 3) {
      const nameLower = s.name.toLowerCase();
      // Check against name
      const nameDist = levenshtein(lowerQuery, nameLower);
      if (nameDist <= Math.max(1, Math.floor(lowerQuery.length / 3))) {
        const fuzzyScore = -10 + (lowerQuery.length - nameDist) * 2;
        if (fuzzyScore > bestScore) {
          bestScore = fuzzyScore;
          bestField = 'name';
        }
      }
      // Also check common names / aliases
      const allNames = [...(s.commonNames || []), ...(s.aliases || [])];
      for (const n of allNames) {
        const nLower = n.toLowerCase();
        // For fuzzy on names, check if query is a prefix (with tolerance)
        if (nLower.length >= lowerQuery.length) {
          const prefix = nLower.substring(0, lowerQuery.length);
          const prefixDist = levenshtein(lowerQuery, prefix);
          if (prefixDist <= Math.max(1, Math.floor(lowerQuery.length / 3))) {
            const fuzzyScore = -10 + (lowerQuery.length - prefixDist);
            if (fuzzyScore > bestScore) {
              bestScore = fuzzyScore;
              bestField = n.length <= 15 ? n : 'name';
            }
          }
        }
      }
    }

    if (bestScore > 0) {
      scored.push({ substance: s, score: bestScore, matchField: bestField });
    }
  }

  // Sort by score descending
  scored.sort((a, b) => b.score - a.score);

  return limit > 0 ? scored.slice(0, limit) : scored;
}

/** Simple Levenshtein distance for fuzzy matching */
function levenshtein(a: string, b: string): number {
  const m = a.length;
  const n = b.length;
  if (m === 0) return n;
  if (n === 0) return m;

  // Use single-row optimization
  let prev = Array.from({ length: n + 1 }, (_, i) => i);
  for (let i = 1; i <= m; i++) {
    const curr = new Array(n + 1);
    curr[0] = i;
    for (let j = 1; j <= n; j++) {
      const cost = a[i - 1] === b[j - 1] ? 0 : 1;
      curr[j] = Math.min(
        prev[j] + 1,       // deletion
        curr[j - 1] + 1,   // insertion
        prev[j - 1] + cost  // substitution
      );
    }
    prev = curr;
  }
  return prev[n];
}

/** Escape special regex characters for use in RegExp */
function escapeSearchRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

export function getAllSubstanceIds(): string[] {
  return substances.map(s => s.id);
}

export function getAllSubstanceNames(): string[] {
  return substances.map(s => s.name);
}

export function getSubstancesByRiskLevel(riskLevel: 'low' | 'moderate' | 'high' | 'very-high'): Substance[] {
  return substances.filter(s => s.riskLevel === riskLevel);
}

export function getSubstancesByRoute(route: string): Substance[] {
  return substances.filter(s => s.routes && s.routes.includes(route));
}

export function getSubstancesByInteraction(interaction: string): Substance[] {
  const lowerInteraction = interaction.toLowerCase();
  return substances.filter(s =>
    s.interactions.some(i => i.toLowerCase().includes(lowerInteraction))
  );
}

export function getSubstanceCount(): number {
  return substances.length;
}

export function getSubstanceCountByCategory(): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const category of Object.keys(substancesByCategory)) {
    counts[category] = substancesByCategory[category].length;
  }
  return counts;
}

// Category constants for convenience
export const CATEGORY_IDS = {
  CANNABINOIDS: 'cannabinoids' as SubstanceCategory,
  DELIRIANTS: 'deliriants' as SubstanceCategory,
  DEPRESSANTS: 'depressants' as SubstanceCategory,
  DISSOCIATIVES: 'dissociatives' as SubstanceCategory,
  EMPATHOGENS: 'empathogens' as SubstanceCategory,
  HALLUCINOGENS: 'hallucinogens' as SubstanceCategory,
  NOOTROPICS: 'nootropics' as SubstanceCategory,
  OPIOIDS: 'opioids' as SubstanceCategory,
  OTHER: 'other' as SubstanceCategory,
  STIMULANTS: 'stimulants' as SubstanceCategory
};

// Risk level constants
export const RISK_LEVELS = {
  LOW: 'low' as const,
  MODERATE: 'moderate' as const,
  HIGH: 'high' as const,
  VERY_HIGH: 'very-high' as const
};
