// Auto-generated from substances.txt
import type { Substance } from '../types';

// Substance Data
// Name: LSD
// ID: lsd
// Categories: hallucinogens
// Class: Lysergamides

export const lsd: Substance = 
{
  "id": "lsd",
  "name": "LSD",
  "commonNames": [
    "LSD",
    "LSD-25",
    "Lucy",
    "L",
    "Acid",
    "Cid",
    "Tabs",
    "Blotter"
  ],
  "categories": [
    "hallucinogens"
  ],
  "class": "Lysergamides",
  "description": "Lysergic acid diethylamide (also known as Lysergide, LSD-25, LSD, L, Lucy, and Acid) is a classical psychedelic substance of the lysergamide class. The psychoactive effects of LSD were first discovered in 1943 by Albert Hofmann at Sandoz Laboratories (Switzerland). In the 1950s, it was widely distributed by Sandoz as an experimental drug for psychotherapy and scientific research; during this era, it provoked considerable interest from the intellectual establishment and was even the subject of a clandestine investigation by the U.S. Central Intelligence Agency (CIA) for potential applications in \"mind control\". Subjective effects include visual geometry / hallucinatory states, time distortion, enhanced introspection, conceptual thinking, increased music appreciation, euphoria, and ego loss.",
  "effects": {
    "positive": [
      "Physical euphoria - A unique form of physical euphoria may occur at certain points of the trip. However, it is limited and inconsistent compared to the effect of entactogens or opioids, and can just as easily manifest as physical discomfort without any apparent reason.",
      "Tactile enhancement - Feelings of enhanced tactile sensations are consistently present at moderate levels throughout most LSD trips.",
      "Bodily control enhancement",
      "Stamina enhancement - The user's stamina for physical activities may be enhanced. Some users have also reported using small doses to improve athletic performance. However, this effect is generally mild compared to the effect of stimulants.",
      "Colour enhancement - Compared to other psychedelics, this effect is often reported to be brighter and more \\\"radiant\\\" in character.",
      "Analysis enhancement - Some users report gaining the ability to analyze situations in novel and relatively objective ways. It is not clear if this is actually the case, or just a feeling generated by the substance.",
      "Cognitive euphoria - Cognitive euphoria is limited and inconsistent compared to that of MDMA, cocaine, and opioids. Unlike the aforementioned substances, mental euphoria on psychedelics is \\\"unforced\\\", meaning it requires a pre-existing positive emotional state.",
      "Euthymia - This effect manifests itself acutely for all classical psychedelics when one to three doses are combined with a psychotherapy treatment program. When comparing meta analyses, psychedelic psychotherapy greatly outperforms \\\"gold standard\\\" treatments for several mental health problems.",
      "Creativity enhancement - LSD is well-known for its ability to enhance creativity and out-of-the-box thinking. A large number of artists, musicians, scientists, and other intellectuals have used it, dating to the 1950s.",
      "Novelty enhancement - Very prominent on LSD compared to other substances.",
      "Focus enhancement - Occurs mostly on low or threshold dosages and feels less forced or sharp than it does with stimulants.",
      "Immersion enhancement - Very prominent on LSD compared to other substances, second only to dissociative immersion enhancement.",
      "Personal meaning enhancement - The user may feel as if their experience has special meaning, which may or may not last after the trip. Appears to depend on the user's set and setting.",
      "Emotion enhancement - The user's ability to experience emotion may be strongly enhanced. This is thought to contribute to its therapeutic effect. Consequently, it is advised to not take LSD when in a low or unstable mood and to follow the principles of set and setting.",
      "Empathy, affection and sociability enhancement - Can be prominent but also unreliable compared to MDMA. More dose-dependent; higher doses are more likely to cause introspection and social withdrawal.",
      "Increased libido - Generally inconsistent compared to stimulants and cannabis. Mild to moderate when it does occur.",
      "Increased music appreciation - Extremely prominent for many users. Likely a part of its therapeutic effect. Sublime or mystical experiences on LSD are often linked to music.",
      "Increased sense of humor - Very common on LSD, particularly during the come up and peak phases. Users report suddenly finding mundane situations and actions inexplicably hilarious.",
      "Laughter fits - Laughter fits are common, particularly during the come up phase. It can manifest as uncontrollable giggles and laughter that can form a feedback loop if around others who are also under the influence.",
      "Motivation enhancement - LSD produces stimulant-like motivation enhancement at low and microdoses, although in a much less prominent or reliable manner.",
      "Suggestibility enhancement - Suggestibility to external influences may be strongly enhanced. While potentially beneficial for psychotherapy, this property can be abused by nefarious individuals (e.g. cult leaders). Users are advised to be discerning about who they take LSD with.",
      "Wakefulness - Users report that it is difficult or impossible to go to sleep for up to 10 hours (or more) after LSD ingestion.",
      "Addiction suppression - Some research suggests LSD can be used to treat addiction. Anecdotally, many users report that psychedelics are helpful for this purpose.",
      "Auditory enhancement - Some users report an enhanced sense of hearing on LSD. However, there is currently no clinical evidence supporting this claim.",
      "Synaesthesia - True synesthesia is rare and non-reproducible, although users often describe the feeling of being able to \\\"hear colors\\\" and \\\"see sounds\\\". Increasing the dosage can increase the likelihood of occurrence, but seems to primarily occur in those who are already predisposed to synesthetic states.",
      "Existential self-realization",
      "Spirituality enhancement",
      "Unity and interconnectedness",
      "Pain relief - LSD can greatly reduce or distort the perception of pain. This is likely due to a variety of factors as the hallucinogenic effects mean that pain can be interpreted as a different sensation (i.e. a tickling sensation from a painful stimulus). <p>LSD also possesses potent anti-inflammatory properties that likely contribute to this effect.",
      "Introspection - Present at most doses. May occur alongside personal bias suppression.",
      "Personal bias suppression - The user may feel they have the ability to analyze their lives or relationships in a more objective way. It is not clear if this is actually the case, or just a feeling generated by the substance."
    ],
    "neutral": [
      "Neurogenesis",
      "Stimulation - LSD is usually described as very energetic and stimulating without being forced. For example, it tends to encourage physical activities such as walking, climbing, or dancing. <p>In comparison, other common psychedelics such as psilocybin or LSA are generally sedating and sedentary.",
      "Spontaneous bodily sensations - The \\\"body high\\\" of LSD behaves as a euphoric, fast-moving, sharp and location specific or generalized tingling sensation.",
      "Perception of bodily lightness - The stimulation and energy LSD produces can cause the user to feel as if they are moving weightlessly.",
      "Changes in felt bodily form - This effect is often accompanied by a sense of warmth or unity and usually near the peak of the experience. Users can feel as if they are physically part of or conjoined with other objects.",
      "Machinescapes - A rare effect that typically only occurs at very strong to heavy doses, and not as consistently as with certain psychedelics such as DMT, psilocybin mushrooms, 2C-P, and atypical psychedelics like salvia.",
      "Thought connectivity - A signature effect. Thoughts may feel more fluid and interconnected than usual. May occur alongside conceptual thinking and creativity enhancement.",
      "Visual acuity enhancement",
      "Pattern recognition enhancement",
      "Magnification",
      "Frame rate enhancement",
      "Drifting (melting, breathing, morphing and flowing) - Compared to other psychedelics, this effect can be described as highly detailed yet cartoon-like in its appearance. The distortions are slow and smooth in motion and fleeting in their appearance.",
      "Colour shifting",
      "Tracers",
      "After images",
      "Depth perception distortions",
      "Environmental patterning",
      "Perspective distortions",
      "Recursion",
      "Symmetrical texture repetition",
      "Scenery slicing",
      "Internal hallucination (autonomous entities; settings, sceneries, and landscapes; perspective hallucinations and scenarios and plots) - Although some users report that LSD is capable of producing hallucinatory states with the same intensity and vividness as psilocybin mushrooms or DMT, it is much rarer and less consistent. While traditional psychedelics such as LSA, ayahuasca and mescaline will induce internal hallucinations near consistently at level 5 geometry and above, some users claim that LSD tends to go straight into Level 8A visual geometry. <p>This lack of consistently induced hallucinatory breakthroughs means that for most, LSD is relatively limited in depth, at doses that do not come with excessive side effects.",
      "External hallucination (autonomous entities; settings, sceneries, and landscapes; perspective hallucinations and scenarios and plots)",
      "Conceptual thinking - A signature effect. LSD may allow the user to bypass normal cognitive patterns (and their associated limitations). Manifests as lateral or abstract thinking patterns.",
      "Simultaneous emotions",
      "Thought acceleration",
      "Time distortion - A signature effect. The user's perception of time may be strongly altered. Typically takes the form of time dilation, or the experience of time slowing down and passing much slower than it does while sober.",
      "Auditory distortion - Sounds may appear \\\"tinny\\\" or \\\"alien\\\". More likely at higher doses.  Certain subjective reports mention flanging, delays/echoing, reverb-like effects, similar to those found in music.",
      "Déjà vu - Unreliable and usually at higher doses. May indicate an overdose and the beginning of delusions and psychosis."
    ],
    "negative": [
      "Transformations",
      "Multiple thought streams",
      "Temperature regulation suppression - LSD appears to cause the body to lose some of its ability to regulate its temperature. While usually harmless, users should be careful when taking LSD in conditions of extreme hot or cold.",
      "Increased bodily temperature  - Potentially dangerous states of overheating have been reported to occur in certain conditions, particularly with higher doses due to the fact that LSD raises body serotonin.",
      "Nausea - Mild nausea is occasionally reported on moderate to high doses and either passes after the user vomits or gradually fades by itself as the peak sets in.",
      "Appetite suppression - LSD can suppress appetite in a manner similar to (although not as strong as) stimulants, especially for fatty foods.",
      "Dehydration - Mild to moderate dehydration may occur. Not as extreme as with stimulants or opioids.",
      "Difficulty urinating",
      "Increased blood pressure - Very rare but can occur in those who are predisposed to them, particularly while in physically taxing conditions such as being dehydrated, undernourished, overheated, or fatigued.",
      "Teeth grinding - Mild to moderate. Not as intense as on MDMA.",
      "Vasoconstriction - Dose-dependent, but weaker compared to stimulants, 25x-NBOMe, or DOx. Some users report feeling cold, especially in the extremities.",
      "Anxiety & Paranoia - Not typically observed at low to common doses and are less likely to occur when the basic rules of set and setting are taken into account.",
      "Delusion - Mild delusions can occur at common doses. Serious, persisting delusions are typically limited to higher doses or individual susceptibility.",
      "Memory suppression - Present at all dose levels past low-common. Stronger than phenethylamines like mescaline or 2C-B but weaker than tryptamines like psilocybin or DMT.",
      "Ego loss - A signature effect. May be accompanied by euphoria or dysphoria depending on set and setting. Also accompanied by time distortion and potentially thought loops.",
      "Ego replacement - Ego replacement is very rare and occurs in an unpredictable manner. This effect usually coincides with delusions and may indicate the beginnings of psychosis. It is more likely to occur with high doses.",
      "Personality regression - True personality regression on LSD is very rare. More commonly, it takes the milder form of the user having strong feelings of early childhood, including repressed memories.",
      "Thought loops - Typically occurs at higher doses, and at the peak of the experience. Often accompanied by ego loss. This effect may become exacerbated or triggered by cannabis or stimulants.",
      "Auditory hallucination - Typically present at higher doses. Not as common as visual hallucinations, but may occur alongside them."
    ]
  },
  "defaultUnit": "µg",
  "routeData": {
    "sublingual": {
      "dosage": {
        "threshold": "15µg",
        "light": "15-75µg",
        "common": "75-150µg",
        "strong": "150-300µg",
        "heavy": "300µg"
      },
      "duration": {
        "onset": "15-30 minutes",
        "comeup": "45-90 minutes",
        "peak": "3-5 hours",
        "offset": "3-5 hours",
        "total": "8-12 hours",
        "afterglow": "12-48 hours"
      }
    }
  },
  "interactions": {
    "dangerous": [
      "Lithium"
    ],
    "unsafe": [
      "Tramadol",
      "Deliriants",
      "Tricyclic antidepressants",
      "Ritonavir"
    ],
    "uncertain": [
      "Cannabis",
      "Stimulants"
    ],
    "crossTolerances": [
      "psychedelics"
    ]
  },
  "harmReduction": [
    "Numerous studies have found that LSD is physiologically well-tolerated and has an extremely low toxicity relative to dose. There is no evidence for long-lasting effects on the brain or other organs and there are no documented deaths attributed to the direct effects of LSD toxicity.",
    "However, it is worth noting that while LSD as a chemical may not be capable of causing direct bodily toxicity or death, its improper use can still present serious hazards.",
    "For example, it has the potential to strongly impair the user's judgment and attention span, which may promote erratic or dangerous behaviors. In extreme cases, the user may experience powerful delusions e.g. that they are currently inside of a dream and therefore physically invincible, or that they are being persecuted by malevolent entities. This may prompt them to jump off of a building or a cliff, or run into oncoming traffic.",
    "Additionally, extreme negative reactions and psychotic episodes (i.e. \"bad trips\") can cause lasting psychological trauma if not properly managed or treated afterward. Extreme negative reactions are uncommon, but are more likely to happen in non-supervised settings and/or with higher doses (i.e. exceeding the \"common\" range).",
    "Finally, it should be noted that evidence of LSD's effectiveness as a mental health treatment only applies to the controlled procedures used in clinical settings. LSD alone is not considered the treatment because the current evidence suggests it must be combined with professional psychotherapy to produce lasting therapeutic effects.",
    "Without the appropriate safeguards, attempts at self-medicating with LSD may actually worsen mental health issues.",
    "It is strongly advised to use harm reduction practices if using this substance. These include:",
    "Taking the substance under the supervision of a tripsitter for one's first time or while experimenting with a higher dose",
    "Starting off with a dose in the low-common range and monitoring for unusual reactions (e.g. mania, delusions) or sensitivity",
    "Not exceeding the listed heavy dose. If heavy doses are required, a tolerance break is advised instead. Heavy doses greatly increase the risk of negative effects",
    "Using a reagent testing kit to verify the substance is genuine LSD and not a dangerous counterfeit",
    "Keeping a supply of benzodiazepines or antipsychotics (e.g. Seroquel) to abort the trip in the case of overwhelming anxiety or psychosis",
    "LSD can exacerbate symptoms (e.g. delusions, mania, psychosis) of various mental disorders. Specifically, it can precipitate the early onset of schizophrenia in vulnerable individuals.",
    "Those with a personal or family history of mental disorders, particularly psychotic disorders like schizophrenia, should not use LSD without consulting a qualified medical professional.",
    "Like other serotonergic psychedelics, LSD is considered to be non-addictive with a low abuse potential. Notably, there are no literature reports of successful attempts to train animals to self-administer a serotonergic psychedelic, which is predictive of abuse liability, indicating that it does not have the necessary pharmacology to either initiate or maintain dependence. Additionally, there is no human clinical evidence that LSD can cause addiction.",
    "There is virtually no withdrawal syndrome when chronic use is stopped. In one study, morphine addicts administered LSD regularly for weeks did not recognize when the drug was exchanged for a placebo and experienced no withdrawal symptoms.",
    "LSD exhibits significant tachyphylaxis; i.e., tolerance to its effects forms almost immediately after ingestion; i.e., in as little as three hours. Human studies from the 1950s and 60s, when LSD was still legal in the United States, found that tolerance to LSD's effects \"requires 3-4 days of daily administration to reach near-maximum levels and 5 days of abstinence to completely reverse.\"",
    "Some anecdotal reports suggest that extremely high doses of LSD can produce a tolerance that can last subsequently longer, anywhere from weeks to months, and that high doses of LSD, along with high tolerances, can produce unusual variations in LSD's intensity, duration, and effects.",
    "LSD also exhibits cross-tolerance with cross-tolerance  all psychedelics, meaning that after the use of LSD, all psychedelics will have a reduced effect.",
    "Unlike other highly prohibited psychoactive substances, LSD has no known toxic dose; it is effectively impossible to physically overdose on. However, higher doses increase the risk of adverse psychological reactions such as anxiety, paranoia, panic attacks, delusions, psychosis, and, in rare cases, seizures.",
    "Medical attention is usually not needed except in the case of severe psychotic episodes or the suspected ingestion of so-called \"fake acid\", substances that mimics LSD's effects but carry the risk of physical toxicity and overdose (e.g. 25x-NBOMe or DOx).",
    "Benzodiazepines (e.g. diazepam (Valium), alprazolam (Xanax)) can help to relieve the acute negative psychological effects of LSD. Antipsychotics such as quetiapine (Seroquel) may also be used, although they have more after-effects and potential interactions. Alcohol can also be used as a last resort, but is generally considered to be less effective than other tripkillers, and is sometimes associated with negative interactions.",
    "The high chemical potency allows LSD to be infused (\"laid\") onto blotter paper for street distribution. It is sometimes counterfeited by certain other psychedelics that also happen to be potent enough to be laid onto blotter paper (while also being cheaper). Colloquially known as \"fake acid\" or \"bunk acid\", the most common adulterant historically is the DOx series, although in recent years the 25x-NBOMe series has become highly prevalent.",
    "Unlike unadulterated LSD blotters, which are usually only mildly bitter or slightly metallic as a byproduct of the blotter paper's ink, mimics are described as having a \"metallic\", \"numbing\", \"chemical-like\", or \"extremely bitter or sour\" taste. It is advised to immediately spit out any blotters that have a strong bitter taste that exceeds a reasonable level.",
    "However, it is important to note that taste testing is not sufficient to fully protect against mimics. Instead, one should always attempt to test their LSD using a . Testing kits are considered vital because the common mimics have significantly worse safety profiles than LSD, including the risk of physical overdose and death.",
    "In rare cases, LSD may trigger hallucinogen persisting perception disorder (HPPD) in some individuals. The cause is unclear; however, explanations in terms of LSD physically remaining in the body for months or years after consumption have been discounted by experimental evidence.",
    "Some say HPPD is a manifestation of post-traumatic stress disorder, not related to the direct action of LSD on brain chemistry, and varies according to the susceptibility of the individual to the disorder.",
    "SSRIs (e.g. fluoxetine, sertraline): Due do the downregulation of 5-HT2A receptors caused by SSRIs, psychedelics can have a reduced effect. Weaker effects could lead to the user compensating by increasing their dose or re-dosing, potentially having stronger effects than they intended. SSRIs can also reduce the chance of having a bad trip due to its anxiolytic effects."
  ],
  "legality": "Legal status varies by jurisdiction. Check local laws.",
  "chemistry": {
    "formula": "Unknown",
    "molecularWeight": "Unknown",
    "class": "Lysergamides"
  },
  "history": "The original synthesis of LSD was recorded on November 16, 1938, by the Swiss chemist Albert Hofmann while employed at the Sandoz Laboratories in Basel, Switzerland. However, it was not discovered to be psychoactive until five years later, when Hofmann claimed to have accidentally ingested an unknown quantity of the chemical before proceeding to ride his bike home. In 1947, Sandoz introduced LSD to the medical community under the name Delysid, marketing it as an experimental tool to induce temporary psychotic-like states in normals (“model-psychosis”) and later to enhance psychotherapeutic treatments (“psycholytic” or “psychedelic” therapy). In the 1950s, the U.S. Central Intelligence Agency (CIA) created a research program code-named MK-ULTRA that would conduct clandestine research investigating LSD for applications in 'mind control' and chemical warfare. Several prominent intellectuals, including Aldous Huxley, Timothy Leary, Al Hubbard, and Alan Watts began to advocate for the mass consumption of LSD; according to L. R. Veysey, they profoundly influenced the thinking of the new generation of youth.",
  "afterEffects": "See route data for afterglow information.",
  "riskLevel": "low"
};